# Generated by Django 4.2.16 on 2026-05-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_menuitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
